# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameter.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fparameter.proto\"\"\n\rELG_Parameter\x12\x11\n\tServiceID\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2A\n\x16Transfer_ELG_Parameter\x12\'\n\rget_ServcieID\x12\x06.Empty\x1a\x0e.ELG_Parameterb\x06proto3'
)




_ELG_PARAMETER = _descriptor.Descriptor(
  name='ELG_Parameter',
  full_name='ELG_Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ServiceID', full_name='ELG_Parameter.ServiceID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['ELG_Parameter'] = _ELG_PARAMETER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ELG_Parameter = _reflection.GeneratedProtocolMessageType('ELG_Parameter', (_message.Message,), {
  'DESCRIPTOR' : _ELG_PARAMETER,
  '__module__' : 'parameter_pb2'
  # @@protoc_insertion_point(class_scope:ELG_Parameter)
  })
_sym_db.RegisterMessage(ELG_Parameter)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'parameter_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_TRANSFER_ELG_PARAMETER = _descriptor.ServiceDescriptor(
  name='Transfer_ELG_Parameter',
  full_name='Transfer_ELG_Parameter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=64,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_ServcieID',
    full_name='Transfer_ELG_Parameter.get_ServcieID',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ELG_PARAMETER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSFER_ELG_PARAMETER)

DESCRIPTOR.services_by_name['Transfer_ELG_Parameter'] = _TRANSFER_ELG_PARAMETER

# @@protoc_insertion_point(module_scope)
