# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: databroker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='databroker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61tabroker.proto\"[\n\x0c\x45LG_Protocol\x12\x17\n\x0f\x42\x65\x66oreServiceID\x18\x01 \x01(\x05\x12\x18\n\x10\x43urrentServiceID\x18\x02 \x01(\x05\x12\x18\n\x10\x41\x66terServicesIDs\x18\x03 \x03(\x05\"V\n\x08\x45LG_Text\x12\x11\n\tPlainText\x18\x01 \x01(\t\x12\x16\n\x0eStructuredText\x18\x02 \x01(\t\x12\x1f\n\x08Protocol\x18\x03 \x01(\x0b\x32\r.ELG_Protocol\"\x07\n\x05\x45mpty22\n\x11Transfer_ELG_Text\x12\x1d\n\x08get_Text\x12\x06.Empty\x1a\t.ELG_Textb\x06proto3'
)




_ELG_PROTOCOL = _descriptor.Descriptor(
  name='ELG_Protocol',
  full_name='ELG_Protocol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BeforeServiceID', full_name='ELG_Protocol.BeforeServiceID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CurrentServiceID', full_name='ELG_Protocol.CurrentServiceID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AfterServicesIDs', full_name='ELG_Protocol.AfterServicesIDs', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=111,
)


_ELG_TEXT = _descriptor.Descriptor(
  name='ELG_Text',
  full_name='ELG_Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PlainText', full_name='ELG_Text.PlainText', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StructuredText', full_name='ELG_Text.StructuredText', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Protocol', full_name='ELG_Text.Protocol', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=199,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=208,
)

_ELG_TEXT.fields_by_name['Protocol'].message_type = _ELG_PROTOCOL
DESCRIPTOR.message_types_by_name['ELG_Protocol'] = _ELG_PROTOCOL
DESCRIPTOR.message_types_by_name['ELG_Text'] = _ELG_TEXT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ELG_Protocol = _reflection.GeneratedProtocolMessageType('ELG_Protocol', (_message.Message,), {
  'DESCRIPTOR' : _ELG_PROTOCOL,
  '__module__' : 'databroker_pb2'
  # @@protoc_insertion_point(class_scope:ELG_Protocol)
  })
_sym_db.RegisterMessage(ELG_Protocol)

ELG_Text = _reflection.GeneratedProtocolMessageType('ELG_Text', (_message.Message,), {
  'DESCRIPTOR' : _ELG_TEXT,
  '__module__' : 'databroker_pb2'
  # @@protoc_insertion_point(class_scope:ELG_Text)
  })
_sym_db.RegisterMessage(ELG_Text)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'databroker_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_TRANSFER_ELG_TEXT = _descriptor.ServiceDescriptor(
  name='Transfer_ELG_Text',
  full_name='Transfer_ELG_Text',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=210,
  serialized_end=260,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_Text',
    full_name='Transfer_ELG_Text.get_Text',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ELG_TEXT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSFER_ELG_TEXT)

DESCRIPTOR.services_by_name['Transfer_ELG_Text'] = _TRANSFER_ELG_TEXT

# @@protoc_insertion_point(module_scope)
