# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import databroker_pb2 as databroker__pb2


class Transfer_ELG_TextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_Text = channel.unary_unary(
                '/Transfer_ELG_Text/get_Text',
                request_serializer=databroker__pb2.Empty.SerializeToString,
                response_deserializer=databroker__pb2.ELG_Text.FromString,
                )


class Transfer_ELG_TextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_Text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Transfer_ELG_TextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_Text': grpc.unary_unary_rpc_method_handler(
                    servicer.get_Text,
                    request_deserializer=databroker__pb2.Empty.FromString,
                    response_serializer=databroker__pb2.ELG_Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transfer_ELG_Text', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transfer_ELG_Text(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transfer_ELG_Text/get_Text',
            databroker__pb2.Empty.SerializeToString,
            databroker__pb2.ELG_Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
