# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import parameter_pb2 as parameter__pb2


class Transfer_ELG_ParameterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_ServcieID = channel.unary_unary(
                '/Transfer_ELG_Parameter/get_ServcieID',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=parameter__pb2.ELG_Parameter.FromString,
                )


class Transfer_ELG_ParameterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_ServcieID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Transfer_ELG_ParameterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_ServcieID': grpc.unary_unary_rpc_method_handler(
                    servicer.get_ServcieID,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=parameter__pb2.ELG_Parameter.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transfer_ELG_Parameter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transfer_ELG_Parameter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_ServcieID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transfer_ELG_Parameter/get_ServcieID',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            parameter__pb2.ELG_Parameter.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
