# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelTextoText.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modelTextoText.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14modelTextoText.proto\"5\n\x08\x45LG_Text\x12\x11\n\tPlainText\x18\x01 \x01(\t\x12\x16\n\x0eStructuredText\x18\x02 \x01(\t\"\"\n\rELG_Parameter\x12\x11\n\tServiceID\x18\x01 \x01(\x05\x32\x62\n\rRunElgService\x12*\n\rInitParameter\x12\x0e.ELG_Parameter\x1a\t.ELG_Text\x12%\n\rRunElgService\x12\t.ELG_Text\x1a\t.ELG_Textb\x06proto3'
)




_ELG_TEXT = _descriptor.Descriptor(
  name='ELG_Text',
  full_name='ELG_Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PlainText', full_name='ELG_Text.PlainText', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StructuredText', full_name='ELG_Text.StructuredText', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=77,
)


_ELG_PARAMETER = _descriptor.Descriptor(
  name='ELG_Parameter',
  full_name='ELG_Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ServiceID', full_name='ELG_Parameter.ServiceID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['ELG_Text'] = _ELG_TEXT
DESCRIPTOR.message_types_by_name['ELG_Parameter'] = _ELG_PARAMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ELG_Text = _reflection.GeneratedProtocolMessageType('ELG_Text', (_message.Message,), {
  'DESCRIPTOR' : _ELG_TEXT,
  '__module__' : 'modelTextoText_pb2'
  # @@protoc_insertion_point(class_scope:ELG_Text)
  })
_sym_db.RegisterMessage(ELG_Text)

ELG_Parameter = _reflection.GeneratedProtocolMessageType('ELG_Parameter', (_message.Message,), {
  'DESCRIPTOR' : _ELG_PARAMETER,
  '__module__' : 'modelTextoText_pb2'
  # @@protoc_insertion_point(class_scope:ELG_Parameter)
  })
_sym_db.RegisterMessage(ELG_Parameter)



_RUNELGSERVICE = _descriptor.ServiceDescriptor(
  name='RunElgService',
  full_name='RunElgService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitParameter',
    full_name='RunElgService.InitParameter',
    index=0,
    containing_service=None,
    input_type=_ELG_PARAMETER,
    output_type=_ELG_TEXT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunElgService',
    full_name='RunElgService.RunElgService',
    index=1,
    containing_service=None,
    input_type=_ELG_TEXT,
    output_type=_ELG_TEXT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RUNELGSERVICE)

DESCRIPTOR.services_by_name['RunElgService'] = _RUNELGSERVICE

# @@protoc_insertion_point(module_scope)
